### ISSUE TITLE
Missing ids throughout the aspect docs

### ISSUE THREAD

**Issue by jimmi-joensson** [teambit/docs#208]
Sections throughout the harmony aspect documents are missing ids. This is problematic when trying to link to specific sections of the docs, either for sharing or support purposes

https://harmony-docs.bit.dev/aspects/compositions

**Comment by debs-obrien** [comment]
yes this is because we are installing this as an mdx component as apposed to just having it live in the docs. We are working on another solution for this where they get generated from the source in bit.dev and then make a pr to the docs repo with the generated doc. This way docusauras will be able to read it better and create the TOC on the side too. For now sorry I know its frustrating. hopefully soon we will have a better solution.

**Comment by jimmi-joensson** [comment]
Okay great to hear a solution is on the way 💪

**Comment by debs-obrien** [comment]
this should be now fixed from this pr: https://github.com/teambit/docs/pull/217
