### ISSUE TITLE
Tutorial - possible missing documentation 

### ISSUE THREAD

**Issue by Aadmaa** [teambit/docs#88]
Just trying to use bit for the first time and running into issue.

I started here: https://harmony-docs.bit.dev/tutorial/install-bit

1. Step 1: install bit - no problem
2. Step 2: create remote scope "demo-scope" with Harmony type - no problem
3. Step 3: set up a Workspace. That's fine until you try "bit start", which bombs as follows:

> Cannot find module '@pmmmwh/react-refresh-webpack-plugin'
> Require stack:   [... Lists webpack.config.js, ui.extension.js, etc. ...]

I tried "bit install" which reports, "Successfully installed 0 component(s)"

Is something missing in the docs?

**Comment by debs-obrien** [comment]
Hi @Aadmaa, yes you are right, I am working on releasing a new version of the docs which will resolve this. Basically this error happens because you do not have a component already created. If you create a component first and then run bit start then this error will go away. We are working on improving this experience too so that this doesn't happen. 

New docs should be ready for release very soon.
I also created a video that might help you see the correct steps of getting things up and running
https://youtu.be/HaKIzYHastU

If you run into any other problems just let us know.

Thanks

**Comment by Aadmaa** [comment]
Thanks
